#!/usr/bin/env python
# -*- coding:utf-8 -*-

# Copyright 2015 Cisco Systems, Inc.
# All rights reserved.

#########################################
# API respone code define
#########################################

SUCCESS = 'SUCCESS'
PARAMETER_ERROR = 'PARAMETER_ERROR'
HTTP_METHOD_INVALID = 'HTTP_METHOD_INVALID'
FABRIC_INVALID = 'FABRIC_INVALID'
OBJECT_ID_INVALID = 'OBJECT_ID_INVALID'
NO_FREE_VNI_TO_ALLOCATE = 'NO_FREE_VNI_TO_ALLOCATE'
DRIVER_NOT_FOUND = 'DRIVER_NOT_FOUND'
TENANT_ID_INVALID = 'TENANT_ID_INVALID'
VNI_TYPE_INVALID = 'VNI_TYPE_INVALID'
CLUSTER_CONFIG_NOT_FOUND = 'CLUSTER_CONFIG_NOT_FOUND'
DEVICE_UNREACHABLE = 'DEVICE_UNREACHABLE'
# Service node management
SERVICE_DEVICE_ALREADY_EXIST = 'SERVICE_DEVICE_ALREADY_EXIST'
SERVICE_DEVICE_NOT_EXIST = 'SERVICE_DEVICE_NOT_EXIST'
SERVICE_DEVICE_NAME_INVALID = 'SERVICE_DEVICE_NAME_INVALID'
SERVICE_DEVICE_ID_INVALID = 'SERVICE_DEVICE_ID_INVALID'
SERVICE_DEVICE_TYPE_INVALID = 'SERVICE_DEVICE_TYPE_INVALID'
CONNECTED_DEVICE_INVALID = 'CONNECTED_DEVICE_INVALID'
SERVICE_DEVICE_HAS_CONNECTED_DEVICES = 'SERVICE_DEVICE_HAS_CONNECTED_DEVICES'
LAYER2_SERVICE_DEVICE_CAN_NOT_BE_UPDATED = 'LAYER2_SERVICE_DEVICE_CAN_NOT_BE_UPDATED'
SERVICE_DEVICE_HAS_L2_ATTACHED = 'SERVICE_DEVICE_HAS_L2_ATTACHED'
PERMENANT_PARAMETER_CAN_NOT_UPDATE = 'PERMENANT_PARAMETER_CAN_NOT_UPDATE'
L2_ATTACHED_OR_HAVE_SERVICE_CHAIN = 'L2_ATTACHED_OR_HAVE_SERVICE_CHAIN'
# FABRIC DEVICE
NBOR_PARAMETER_ERROR = "NBOR_PARAMETER_ERROR"
VTEP_PARAMETER_ERROR = "VTEP_PARAMETER_ERROR"
DEVICE_NOT_EXIST = 'DEVICE_NOT_EXIST'
DEVICE_ID_INVALID = 'DEVICE_ID_INVALID'
DEVICE_HAS_L2_ATTACHED = 'DEVICE_HAS_L2_ATTACHED'
DEVICE_HAS_SERVICE_DEVICE_ATTACHED = 'DEVICE_HAS_SERVICE_DEVICE_ATTACHED'
UNSUPPORTED_DEVICE_INCLUDED = "UNSUPPORTED_DEVICE_INCLUDED"
SPINE = "SPINE"
LEAF = "LEAF"
DEVICE_ROLE_TYPE = (SPINE, LEAF)
DEVICE_ROLE_ERROR = "DEVICE_ROLE_ERROR"
# FABRIC
FABRIC_ID_INVALID = 'FABRIC_ID_INVALID'
FABRIC_NAME_INVALID = 'FABRIC_NAME_INVALID'
CURRENT_FABRIC_FORBIDDEN = 'CURRENT_FABRIC_FORBIDDEN'
DEFAULT_FABRIC_FORBIDDEN = 'DEFAULT_FABRIC_FORBIDDEN'
FABRIC_L2_VNI_POOL_INVALID = 'FABRIC_L2_VNI_POOL_INVALID'
FABRIC_L3_VNI_POOL_INVALID = 'FABRIC_L3_VNI_POOL_INVALID'
FABRIC_VLAN_POOL_INVALID = 'FABRIC_VLAN_POOL_INVALID'
FABRIC_NAMING_RULE_INVALID = 'FABRIC_NAMING_RULE_INVALID'
FABRIC_MAC_INVALID = 'FABRIC_MAC_INVALID'
FABRIC_MGROUP_INVALID = 'FABRIC_MGROUP_INVALID'
FABRIC_ASN_INVALID = 'FABRIC_ASN_INVALID'
FABRIC_ALREADY_EXIST = 'FABRIC_ALREADY_EXIST'
FABRIC_NOT_EXIST = 'FABRIC_NOT_EXIST'
FABRIC_HAS_OBJECT_CREATED = 'FABRIC_HAS_OBJECT_CREATED'
FABRIC_HAS_DEVICE_DEPLOYED = 'FABRIC_HAS_DEVICE_DEPLOYED'
FABRIC_PARAMETERS_INVALID = 'FABRIC_PARAMETERS_INVALID'
FABRIC_BGP_TYPE_INVALID = 'FABRIC_BGP_TYPE_INVALID'
FABRIC_DEDICATED_SPINE_INVALID = 'FABRIC_DEDICATED_SPINE_INVALID'
FABRIC_NVE_SRC_INTERFACE_INVALID = 'FABRIC_NVE_SRC_INTERFACE_INVALID'
FABRIC_SUPPRESS_ARP_INVALID = 'FABRIC_SUPPRESS_ARP_INVALID'
FABRIC_BUM_TYPE_INVALID = 'FABRIC_BUM_TYPE_INVALID'
# MAC
HOST_INVALID = 'HOST_INVALID'

# MAC
MAC_INVALID = 'MAC_INVALID'

# BGP
ASN_ERROR = 'ASN_ERROR'
EBGP = 'EBGP'
IBGP = 'IBGP'
BGP_TYPE = (EBGP, IBGP)

# TAG
TAG_INVALID = 'TAG_INVALID'

# LOG TYPE
LOG_TYPE_INVALID = 'LOG_TYPE_INVALID'
ACTION_LOG = 'ACTION_LOG'
DEVICE_LOG = 'DEVICE_LOG'
DATABASE_LOG = 'DATABASE_LOG'
RESTAPI_LOG = 'RESTAPI_LOG'
LOG_TYPE_LIST = (ACTION_LOG, DEVICE_LOG, DATABASE_LOG, RESTAPI_LOG)

# LEAF DEVICE
LEAF_DEVICE_NOT_EXIST = 'LEAF_DEVICE_NOT_EXIST'
LEAF_NOT_CONNECTED_TO_SERVICE_DEVICE = 'LEAF_NOT_CONNECTED_TO_SERVICE_DEVICE'
L2_VLAN_OCCUPIED = 'L2_VLAN_OCCUPIED'
L2_VLAN_OUT_OF_RANGE = 'L2_VLAN_OUT_OF_RANGE'
L2_VLAN_EXHAUSTED = 'L2_VLAN_EXHAUSTED'
L3_VLAN_OCCUPIED = 'L3_VLAN_OCCUPIED'
L3_VLAN_OUT_OF_RANGE = 'L3_VLAN_OUT_OF_RANGE'
L3_VLAN_EXHAUSTED = 'L3_VLAN_EXHAUSTED'
# tenant
TENANT_TYPE_INVALID = "TENANT_TYPE_INVALID"
TENANT_ALREADY_EXIST = "TENANT_ALREADY_EXIST"
TENANT_VNI_INVALID = 'TENANT_VNI_INVALID'
TENANT_NOT_EXIST = 'TENANT_NOT_EXIST'
TENANT_L3_VNI_INVALID = 'TENANT_L3_VNI_INVALID'
TENANT_NAME_INVALID = 'TENANT_NAME_INVALID'
TENANT_WITH_L2_CAN_NOT_UPDATE = 'TENANT_WITH_L2_CAN_NOT_UPDATE'
TENANT_TYPE_CAN_NOT_UPDATE = 'TENANT_TYPE_CAN_NOT_UPDATE'
TENANT_NAME_CAN_NOT_UPDATE = 'TENANT_NAME_CAN_NOT_UPDATE'
TENANT_VNI_CAN_NOT_UPDATE = 'TENANT_VNI_CAN_NOT_UPDATE'
TENANT_DISPLAY_NAME_INVALID = 'TENANT_DISPLAY_NAME_INVALID'
TENANT_DISPLAY_NAME_ALREADY_EXIST = 'TENANT_DISPLAY_NAME_ALREADY_EXIST'
TENANT_ALREADY_EXIST_OR_DUPLICATE = "TENANT_ALREADY_EXIST_OR_DUPLICATE"
# delete
FORCE = "FORCE"
DELETE_TYPE = (FORCE)
DELETE_TYPE_INVALID = "DELETE_TYPE_INVALID"

# l2
L2_ID_INVALID = 'L2_ID_INVALID'
RD_ERROR = 'RD_ERROR'
RT_ERROR = 'RT_ERROR'
L2_BUM_MULTICAST = 'MULTICAST'
L2_BUM_INGRESS_REPLICATION = 'L2_BUM_INGRESS_REPLICATION'
L2_BUM_TYPE = (L2_BUM_MULTICAST, L2_BUM_INGRESS_REPLICATION)
L2_BUM_TYPE_INVALID = 'L2_BUM_TYPE_INVALID'
L2_TYPE_INVALID = 'L2_TYPE_INVALID'
L2_ALREADY_EXIST = 'L2_ALREADY_EXIST'
L2_VNI_INVALID = 'L2_VNI_INVALID'
SERVICE_CHAIN_INVALID = 'SERVICE_CHAIN_INVALID'
ATTACH_INVALID = 'ATTACH_INVALID'
L3_ROUTING_INVALID = 'L3_ROUTING_INVALID'
L3_ROUTING_OVERLAPS = 'L3_ROUTING_OVERLAPS'
ROUTE_FORMAT_INVALID = 'ROUTE_FORMAT_INVALID'
L2_NOT_EXIST = 'L2_NOT_EXIST'
IP_MASK_FORMAT_INVALID = 'IP_MASK_FORMAT_INVALID'
L2_NAME_ALREADY_EXIST = 'L2_NAME_ALREADY_EXIST'
L2_ATTACHED = 'L2_ATTACHED'
L2_DEPLOYED = 'L2_DEPLOYED'
L2_DISPLAY_NAME_INVALID = 'L2_DISPLAY_NAME_INVALID'
L2_NAME_INVALID = 'L2_NAME_INVALID'
L2_ALREADY_EXIST_OR_DUPLICATE = 'L2_ALREADY_EXIST_OR_DUPLICATE'
STATIC_ROUTES_FOR_SERVICE_CHAIN_INVALID = 'STATIC_ROUTES_FOR_SERVICE_CHAIN_INVALID'
SERVICE_CHAIN_PROTOCOL_TYPE_INVALID = 'SERVICE_CHAIN_PROTOCOL_TYPE_INVALID'
SERVICE_CHAIN_BGP_PEER_AS_INVALID = 'SERVICE_CHAIN_BGP_PEER_AS_INVALID'
SERVICE_CHAIN_BGP_NETWORK_INVALID = 'SERVICE_CHAIN_BGP_NETWORK_INVALID'
SERVICE_CHAIN_BGP_NEIGHBOR_INVALID = 'SERVICE_CHAIN_BGP_NEIGHBOR_INVALID'

SERVICE_CHAIN_OSPF_ID_INVALID = 'SERVICE_CHAIN_OSPF_ID_INVALID'
SERVICE_CHAIN_OSPF_AREA_ID_INVALID = 'SERVICE_CHAIN_OSPF_AREA_ID_INVALID'
SERVICE_CHAIN_OSPF_NETWORK_INVALID = 'SERVICE_CHAIN_OSPF_NETWORK_INVALID'
OSPF_PROCESS_ID_CONFLICT = 'OSPF_PROCESS_ID_CONFLICT'
OSPF_AREA_ID_CONFLICT = 'OSPF_AREA_ID_CONFLICT'

OTHER_DEPLOY_IS_RUNNING = 'OTHER_DEPLOY_IS_RUNNING'
SNAPSHOT_TYPE_IS_NOT_DEPLOY = 'SNAPSHOT_TYPE_IS_NOT_DEPLOY'
SNAPSHOT_EXPIRE = 'SNAPSHOT_EXPIRE'
SNAPSHOT_NOT_FOUND = 'SNAPSHOT_NOT_FOUND'

DEPLOY_ERROR_ON_SOME_DEVICE = 'DEPLOY_ERROR_ON_SOME_DEVICE'

VPC_PEER_MUST_INCLUDED = 'VPC_PEER_MUST_INCLUDED'
#########################################
# Other
#########################################
SERVICE_DEVICE_TYPE_FW = 'FW'
SERVICE_DEVICE_TYPE_LB = 'LB'
SERVICE_DEVICE_TYPE_ROUTER = 'ROUTER'
SERVICE_DEVICE_TYPE_EXT_DCI = 'EXT/DCI'
SERVICE_DEVICE_TYPE = (
    SERVICE_DEVICE_TYPE_FW, SERVICE_DEVICE_TYPE_LB, SERVICE_DEVICE_TYPE_ROUTER, SERVICE_DEVICE_TYPE_EXT_DCI)
TENANT_TYPE_BUSINESS = 'BUSINESS'
TENANT_TYPE_CORE = 'CORE'
TENANT_TYPE_EXTERNAL = 'EXTERNAL'
TENANT_TYPE = (TENANT_TYPE_BUSINESS, TENANT_TYPE_CORE, TENANT_TYPE_EXTERNAL)
OBJECT_TYPE_TENANT = 'TENANT'
OBJECT_TYPE_DEVICE = 'DEVICE'
OBJECT_TYPE_L2 = 'L2'
OBJECT_TYPE_L2_SERVICE_CHAIN = 'L2_SERVICE_CHAIN'
UNKNOW_ERROR = 'UNKNOW_ERROR'
#########################################
# Database
#########################################
DATABASE_TYPE = 'MARIADB'
#########################################
# DISCOVRY
#########################################
AUTO_DISCOVERY = "AUTO"
MANUAL_DISCOVRY = "MANUAL"
FILE_DISCOVERY = "FILE"
DISCOVERY_TYPE = (AUTO_DISCOVERY, MANUAL_DISCOVRY, FILE_DISCOVERY)
DISCOVERY_TYPE_INVALID = "DISCOVERY_TYPE_INVALID"
SEED_IP_INVALID = "SEED_IP_INVALID"
ACCESS_INVALID = "ACCESS_INVALID"
DEVICE_AUTH_FAILED = "DEVICE_AUTH_FAILED"
DEVICE_UNREACHABLE = "DEVICE_UNREACHABLE"
DEVICE_INTERNAL_ERROR = "DEVICE_INTERNAL_ERROR"
DEVICE_VERSION_UNSUPPORTED = "DEVICE_VERSION_UNSUPPORTED"
FILE_INVALID = "FILE_INVALID"
FILE_FORMAT_ERROR = "FILE_FORMAT_ERROR"
#########################################
# AUTH
#########################################
NO_USERNAME_OR_PASSWORD = "NO_USERNAME_OR_PASSWORD"
USER_AND_PASSWD_INCORRECT = "USER_AND_PASSWD_INCORRECT"
USER_PERMISSION_LIMITED = "USER_PERMISSION_LIMITED"
USER_FABRIC_ERROR = "USER_FABRIC_ERROR"
USER_DISABLED = "USER_DISABLED"
HTTP_AUTHORIZATION_ERROR = "HTTP_AUTHORIZATION_ERROR"
TOKEN_FORMAT_ERROR = "TOKEN_FORMAT_ERROR"
#########################################
# USER
#########################################
PARAMETER_ERROR = "PARAMETER_ERROR"
ADMIN = "ADMIN"
STAFF = "STAFF"
ROLE_TYPE = (ADMIN, STAFF)
USER_ROLE_ERROR = "USER_ROLE_ERROR"
USER_NOT_EXSIT = "USER_NOT_EXSIT"
USER_IS_SUPERUSER = "USER_IS_SUPERUSER"
CURRENT_USER = "CURRENT_USER"
USER_INTERNAL_ERROR = "USER_INTERNAL_ERROR"
USER_PERMISSION_LIMITED = "USER_PERMISSION_LIMITED"
NO_FABRIC_LIST = "NO_FABRIC_LIST"
NO_DEFAULT_FABRIC = "NO_DEFAULT_FABRIC"
USER_ALREADY_EXIST = "USER_ALREADY_EXIST"
#########################################
# TOPOLOGY
#########################################
DISCOVERY = "DISCOVERY"
TOPOLOGY_TYPE = (DISCOVERY)
TOPOLOGY_TYPE_INVALID = "TOPOLOGY_TYPE_INVALID"
#########################################
# UI LOCATIONS
#########################################
DAY2 = "DAY2"
DESIGN = "DESIGN"
# UI_TYPE = (DAY2, DESIGN)
UI_TYPE = (DAY2,)
DEVICE = "DEVICE"
SERVICE_DEVICE = "SERVICE_DEVICE"
LAYER2 = "LAYER2"
TENANT = "TENANT"
OBJECT_TYPE = (DEVICE,)
# OBJECT_TYPE = (DEVICE, SERVICE_DEVICE, LAYER2, TENANT)
UI_TYPE_INVALID = "UI_TYPE_INVALID"
OBJECT_TYPE_INVALID = "OBJECT_TYPE_INVALID"
OBJECT_NOT_EXIST = "OBJECT_NOT_EXIST"
#########################################
# SERVER
#########################################
SERVER_IP_INVALID = "SERVER_IP_INVALID"
LEAF_IP_INVALID = "LEAF_IP_INVALID"
SERVER_ALREADY_EXIST_OR_DUPLICATE = 'SERVER_ALREADY_EXIST_OR_DUPLICATE'
LEAF_ALREADY_EXIST_OR_DUPLICATE = 'LEAF_ALREADY_EXIST_OR_DUPLICATE'
#########################################
# Configuration
#########################################
SYSLOG_INVALID = "SYSLOG_INVALID"
#########################################
# Operations
#########################################
BGP_DEVICE_UNREACHABLE = 'BGP_DEVICE_UNREACHABLE'
