# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-21 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(blank=True, max_length=200, null=True)),
                ('col2', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
