# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-21 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apolo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_table1',
            name='col3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
